<?php

namespace AppBundle\Entity;

/**
 * ExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseRepository extends \Doctrine\ORM\EntityRepository
{
	public function countTotalRows($musclegroup = 'All')
	{
		$qb = $this->createQueryBuilder('ex')
					->select('count(ex.id)');
					
		if('All' != $musclegroup)
		{
			$qb->andWhere('ex.muscleGroup LIKE :group' )
				->setParameter('group', "%{$musclegroup}%")
				->addOrderBy('ex.rating', 'DESC');
		}

		return $qb->getQuery()->getSingleScalarResult();
	}

	public function findByLimitOffset($limit, $offset, $musclegroup = 'All')
	{

		$qb = $this->createQueryBuilder('ex');

		if ('All' != $musclegroup)
		{
			$qb->andWhere('ex.muscleGroup LIKE :group')
				->setParameter('group', "%{$musclegroup}%")
				->addOrderBy('ex.rating', 'DESC');
		}

		$qb->setFirstResult($offset)
			->setMaxResults($limit);

		return $qb->getQuery()->getResult();

	}
}
